import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:html_editor_enhanced/html_editor.dart';
import 'package:file_picker/file_picker.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'package:meows_co/data/models/models.dart';
import 'package:meows_co/data/services/services.dart';
import 'package:meows_co/ui/widgets/widgets.dart';
import 'package:provider/provider.dart';
import '../../shared/shared.dart';
import '../../bussines_logic/blocs/blocs.dart';

part 'splashscreen_page.dart';
part 'signup_page.dart';
part 'signin_page.dart';
part 'home_page.dart';
part 'main_page.dart';
part 'search_page.dart';
part 'detail_article_page.dart';
part 'new_post_page.dart';
part 'setting_page.dart';
part 'post_detail_page.dart';
part 'profile_page.dart';
part 'list_post_page.dart';
part 'list_article_page.dart';
part 'coming_soon_page.dart';
part 'verify_email_page.dart';
part 'mycat_pages.dart';

